### PR TITLE
Dart Migration w/o annotations

### PR DESCRIPTION
**Pull request by MateusAmin**
https://github.com/nabil6391/graphview/issues/21

Not tested, but passes analysis. I am using in my own project and will follow up with opinions. 

I used the Dart migration tools without any annotation coloring the results. Then made some patches here and there.  You may want to go through it yourself as there is an opportunity to make the API a bit safer by shifting types to be non-nullable. Without annotations the migration tends to just make things explicitly null able. 

Also, probably a good idea to major version bump and add a -beta tag to the version if you feel this is still in beta.

### CODE REVIEW

**Comment by MateusAmin** [comment]
It works with some minor use changes, would need to update the examples.

Honestly, this is a pretty low effort PR from my end. If someone has time to really think things through that would be best.

**Comment by nabil6391** [comment]
hi @MateusAmin , really busy month going on for me, I wont be able to CR soon. Hope you understand

**Comment by MateusAmin** [comment]
Absolutely. If I where less busy I would have made you a cleaner PR. Hopefully, some other users with more time might step in. 

With my use case I am going to end up with a custom library but this really helped me get off to a quick start. I am grateful for all the work you put into this so far.

**Comment by stefanschaller** [comment]
What is the progress right now? 
My company would like to use / fork this repo to do something awesome (When Null-Safefy is done and stable)

Is any help needed?

**Comment by nabil6391** [comment]
I have pushed some codes to master for a change. After merging I will make this null safe

**Comment by vin-fandemand** [comment]
Hi folks, any update on the null safe release?

**Comment by nabil6391** [comment]
NullSafety version has been released guys, thanks for the wait
Version: 1.0.0-nullsafety.1

**Pull request closed without merging**
